### ISSUE TITLE
Intensity used for Q/I, U/I, and Ltot/I in daily movies

### ISSUE THREAD

**Issue by detoma** [NCAR/comp-pipeline#127]
In `comp_l2_create_movies.pro`, the intensity used in the ratio of Q/I, U/I, Ltot/I should be the average intensity from the level 2 polarization file, not from the dynamic file.

**Comment by detoma** [comment]
Verify equation for Q and U. Should be the same weighted average used for I in polarization file.

**Comment by mgalloy** [comment]
@detoma: I had changed this to use the center line intensity from the level 1 file after one of our meetings recently. Where should I get the intensity from?

**Comment by mgalloy** [comment]
If the level 1 file only has I and V, there will not be a polarization file. Should I use the dynamics file or the level 1 center line? or not produce the frame?

**Comment by mgalloy** [comment]
Ah, actually the pipeline doesn't need the polarization file I if there is no Q and U (and hence L) to normalize.

**Comment by mgalloy** [comment]
823f14a2ccfc569dee3d8c0851f05a2f5566b0d8 has the fix for this, to not look for polarization file if the pipeline does need it.
