### ISSUE TITLE
Produce intermediate product for 20120328

### ISSUE THREAD

**Issue by mgalloy** [NCAR/comp-pipeline#142]
Produce an intermediate product of the two beams just before they are combined:

> The 2012 data without distortion look fuzzy, as expected.
>
> The difference between the old and new distortion is subtle. Likely neither one is perfect. To decide between the old and new distortion I need intermediate products, namely:
> the two beams (with new and old distortion applied) just before they are combined. so I can make a difference between the two beams.
> 
> I only need one day for this: 20120328.

Both `fgplus` and `fgminus` from `COMP_COMBINE_BEAMS` need to be saved. This needs to be done with old and new distortion corrections.

**Comment by mgalloy** [comment]
New results with intermediate products are in engineering.{new,old}-distortion/2012/03/28. This is related to #138.

**Comment by detoma** [comment]
Both Joan and I looked at the intermediate products. This is completed.

**Comment by mgalloy** [comment]
Can I remove the output?

**Comment by detoma** [comment]
yes

**Comment by mgalloy** [comment]
Output has been deleted.
