### ISSUE TITLE
Fix coordinate keyword in L1 header

### ISSUE THREAD

**Issue by mgalloy** [NCAR/comp-pipeline#29]
See KCor as an example of standard.

This will be implemented when the Q/U polarimetry are consistent with the heliographic coordinate system.

**Comment by mgalloy** [comment]
Joan says:

> I've attached a quick-loop excel spread sheet that contains the CoMp and KCor coordinate system keywords that Mike sent me in his email below and I added the KCor INST_ROT keyword.

> Green type in the excel spread sheet represents equivalent keywords and usage between kcor and CoMP. No changes are required.

> Black: The CoMP keywords in black are specific to CoMP and are fine as is.

> Red:  There are a few out-dated keywords or values in CoMP and they are highlighted in red:

> 1) COORDNAM  should be replaced with 'WCSNAME'  'helioprojective-cartesian' /World Coordinate System (WCS) name  
> 2) CROTA1 / CROTA2   should be replaced with PCi_j     (See KCor for example)
> 3) CTYPE1 and CTYPE2 keyword is ok but value ('X', "Y") should be replaced with: 'HPLN-TAN' / [deg] helioprojective west angle: solar X (or Y)   

> These changes should certainly be put in the UCoMP headers. For CoMP we can do one of two things:

> 1)  Make the changes in UCoMP headers only and leave CoMP as is.
            If selected, we should add a keyword in CoMP header so we know which images have the Q,U, polarimetric transform to helio.

> 2) Make the 3 changes to CoMP and ensure the pipeline doesn't break. We need to let Sarah / Steve know BEFORE we do this.

> I am okay either way as long as we are consistent. 
[COMP vs KCOR KEYWORDS FITS HEADERS.xlsx](https://github.com/ncar-mlso/comp-pipeline/files/545108/COMP.vs.KCOR.KEYWORDS.FITS.HEADERS.xlsx)

**Comment by mgalloy** [comment]
Giuliana says:

> I would made the changes in UCOMP. These new keywords do not seem widely used.
There are solarsoft routines that use CROTA1/ CROTA2. I have never seen them replaced with PCi_j. 
Do you know of any instrument, beside KCor, that has adopted them yet?
CORDNAM is also more common than WCSNAME. Let's keep it for now.

**Comment by jburkepile** [comment]
I agree. Let's apply the new keywords in UCoMP. ( STEREO mission uses them and so will Solar Probe and Solar Orbiter)
BUT we should add a keyword to the current CoMP headers so we know when Mike has reprocessed Q,U with the polarimetric helio transform. Since that is unique to CoMP we can call the keyword whatever we want.

**Comment by mgalloy** [comment]
I'm going reopen and move to a UCoMP milestone for next year.

**Comment by mgalloy** [comment]
I added #32 for an L1 keyword indicating how the Q/U were processed.
