### ISSUE TITLE
Distribute 1083 to archive 

### ISSUE THREAD

**Issue by jburkepile** [NCAR/comp-pipeline#51]
Want to deliver line center intensity FITS files, scaled images (e.g. png, jpg, or gif), daily movies (MPEG/GIF), and "good" text files.

**Comment by mgalloy** [comment]
Turn on 1079 and 1083 for `COMP_EXTRACT_INTENSITY`, but make sure to only distribute 1074 non-background GIFs. Also, create 1083 line center FTS files and distribute them.

**Comment by mgalloy** [comment]
Create 1083 line center intensity FTS files:

- use same primary header
- use data/header from the extension for line center intensity
- distribute them to archive
- add them into the 1083 L1 tarball
