### ISSUE TITLE
Fill flat under the occulter with median value

### ISSUE THREAD

**Issue by detoma** [NCAR/comp-pipeline#66]
Filling the flat under the occulter with the median flat value inside the annulus does not seem to work properly. Level 1 images seem too bright where the image occulter does not align with the flat occulter. This could be a consequence of the flat center being incorrect. After the flat center is fixed, we must check if the flat are filled properly under the occulter with the median value and how the level 1 images look. If using the median value does not improve the appearance of the level 1 images, a different median for each sector shall be used.

In the GIF image of the flat that shows the location of the post, the flat should be filled, so we can quickly see how well the filling works.

**Comment by detoma** [comment]
This is not as simple as using quadrants. To properly fill the flat, we should fit the gradient in the flat image

**Comment by mgalloy** [comment]
Use `COMP_FIX_TREND` results to make a smooth fill under the occulter.
