### ISSUE TITLE
HeI center

### ISSUE THREAD

**Issue by detoma** [NCAR/comp-pipeline#68]
HeI images that are summed over the two beams are often not co-aligned properly. This is likely not a problem with the centering routine but with how the center is passed to other programs. This could be  true for the other two coronal lines  but less noticeable in the coronal images.

**Comment by detoma** [comment]
HeI continuum too faint to find center. could try to use HeI line but likely to fail also.
Best option is to use data taken with the clear filter. It would rwquire to reprocess HeI at the end of the day.

**Comment by mgalloy** [comment]
Try using the corona beam instead of the background beam.

**Comment by mgalloy** [comment]
Don't combine beams for 1083.

**Comment by mgalloy** [comment]
Test on `.he-centering` dates.
