### ISSUE TITLE
function "comp_find_average_files_findclusters" missing  in "comp_find_average_files.pro"

### ISSUE THREAD

**Issue by janrybakchoc** [NCAR/comp-pipeline#94]
Dear Michael,

working with your comp-pipeline I have found that function  "comp_find_average_files_findclusters" is missing  in "comp_find_average_files.pro" used for handling the level2 calibration of the CoMP data.

Could you give me an advice how to overcome this problem?

Jan Rybak

Information from the ...comp.log file:

    2020-07-06 17:46:08 CRITICAL: COMP_AVERAGE: Stack trace for error
    % Attempt to call undefined function: 'COMP_FIND_AVERAGE_FILES_FINDCLUSTERS'.
    % Execution halted at:  COMP_FIND_AVERAGE_FILES  458 /home/choc/idl/idl_libs/comp-pipeline_test_jr_1/src/level2/comp_find_average_files.
    %                       COMP_AVERAGE      102 /home/choc/idl/idl_libs/comp-pipeline_test_jr_1/src/level2/comp_average.pro
    %                       COMP_RUN_PIPELINE  427 /home/choc/idl/idl_libs/comp-pipeline_test_jr_1/src/comp_run_pipeline.pro
    %                       $MAIN$
    2020-07-06 17:46:08 ERROR: COMP_RUN_PIPELINE: error with creating wave averages, stopping day
    2020-07-06 17:46:08 INFO: COMP_RUN_PIPELINE: total running time: 42 mins 55 secs

**Comment by mgalloy** [comment]
I added the routine back in 01d892f146eb86345007d313af1e1f62b64e59c9 today. It was removed and not noticed because we don't run in empirical crosstalk calculation mode hardly ever, and it is only usually used in that mode.

**Comment by janrybakchoc** [comment]
Dear Michael, thanks a lo for your routine. Now all works properly.
With the best wishes Jan Rybak
